# Generated by Django 4.2.14 on 2024-07-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("location_image", models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="dates",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="price",
        ),
        migrations.AddField(
            model_name="airport",
            name="airport_lattitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="airport",
            name="airport_longitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(default="2023-01-01 00:00:00"),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(default="2023-01-01 00:00:00"),
        ),
        migrations.AddField(
            model_name="pilot",
            name="availiabe",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="promotion_code",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="promotion",
            name="promotion_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="promotion",
            name="promotion_end_date",
            field=models.DateField(default="2023-01-01"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="promotion_name",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="promotion",
            name="promotion_start_date",
            field=models.DateField(default="2023-01-01"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="route",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="core.route"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="image_url",
            field=models.URLField(default="https://via.placeholder.com/300x200"),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="PilotAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.pilot"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="airport",
            name="airport_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.location"
            ),
        ),
    ]
